USE [master]
GO

/****** Object:  Database [VendingMachine]    Script Date: 1/14/2019 6:04:06 PM ******/
CREATE DATABASE [VendingMachine]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VendingMachine', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\VendingMachine.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VendingMachine_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\VendingMachine_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [VendingMachine] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VendingMachine].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [VendingMachine] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [VendingMachine] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [VendingMachine] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [VendingMachine] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [VendingMachine] SET ARITHABORT OFF 
GO

ALTER DATABASE [VendingMachine] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [VendingMachine] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [VendingMachine] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [VendingMachine] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [VendingMachine] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [VendingMachine] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [VendingMachine] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [VendingMachine] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [VendingMachine] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [VendingMachine] SET  DISABLE_BROKER 
GO

ALTER DATABASE [VendingMachine] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [VendingMachine] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [VendingMachine] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [VendingMachine] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [VendingMachine] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [VendingMachine] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [VendingMachine] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [VendingMachine] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [VendingMachine] SET  MULTI_USER 
GO

ALTER DATABASE [VendingMachine] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [VendingMachine] SET DB_CHAINING OFF 
GO

ALTER DATABASE [VendingMachine] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [VendingMachine] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [VendingMachine] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [VendingMachine] SET QUERY_STORE = OFF
GO

USE [VendingMachine]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [VendingMachine] SET  READ_WRITE 
GO


